# Site
name: 'MMDG'
description: 'Sitio oficial del Museo Municipal de Guayaquil'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: 'mmdg.site'
disqus: ''
email: 'fmayorga.uno@gmail.com'
mailchimp-list: 'https://mailchi.mp/d79a2ece6906/mmdg'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    fernando:
      name:           "Fernando Mayorga"
      site:           https://fernanz.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Fernando Mayorga, diseñador web y profesor universitario, amigo de la Historia del Arte y el Patrimonio Cultural ecuatoriano."
      email:          fmayorga.uno@gmail.com
      twitter:        https://twitter.com/fernanz

    jane:
      name:           "Jane Foster"
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Fernando
      avatar: '/assets/images/avatar1.jpg'

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5

collections:
  arts:
    output: true

defaults:
  - scope:
      type: arts
    values:
      layout: ars

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
